# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ssm-params" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c20c30421bffeb7a390b22ddd518c4d462c80f494ce588a70aee68c6e7e5cd3a"
      url "https://github.com/biptec/aws-ssm-params/releases/download/v#{version}/aws-ssm-params-v#{version}-darwin-amd64.tar.gz"
      rename "aws-ssm-params-v0.3.0-darwin-amd64/aws-ssm-params", "aws-ssm-params"
    end
    on_arm do
      sha256 "ed8dd9b5c3f355fa627a27e159fc805c5f900d0e9d1f67d84fa9be6b7495840b"
      url "https://github.com/biptec/aws-ssm-params/releases/download/v#{version}/aws-ssm-params-v#{version}-darwin-arm64.tar.gz"
      rename "aws-ssm-params-v0.3.0-darwin-arm64/aws-ssm-params", "aws-ssm-params"
    end
  end

  on_linux do
    on_intel do
      sha256 "63b23c2617c86120d14deb48c24703e2f315fc14318a47460785ae2a0b919975"
      url "https://github.com/biptec/aws-ssm-params/releases/download/v#{version}/aws-ssm-params-v#{version}-linux-amd64.tar.gz"
      rename "aws-ssm-params-v0.3.0-linux-amd64/aws-ssm-params", "aws-ssm-params"
    end
    on_arm do
      sha256 "61d11f7e8e292e620c90d673ef799f082274c5489bdd824e4936bce0d33ca0b3"
      url "https://github.com/biptec/aws-ssm-params/releases/download/v#{version}/aws-ssm-params-v#{version}-linux-arm64.tar.gz"
      rename "aws-ssm-params-v0.3.0-linux-arm64/aws-ssm-params", "aws-ssm-params"
    end
  end

  name "aws-ssm-params"
  desc "CLI/TUI for AWS SSM Parameter Store values"
  homepage "https://github.com/biptec/aws-ssm-params"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ssm-params"

  # No zap stanza required

  caveats <<~EOS
    To get started:
      aws-ssm-params --help
  EOS
end
