# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsmParams < Formula
  desc "Terminal UI and CLI for AWS SSM Parameter Store"
  homepage "https://github.com/biptec/aws-ssm-params"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.4.1/aws-ssm-params-v0.4.1-darwin-amd64.tar.gz"
      sha256 "4a3ee2ee0a7a590f2c823facd7e948178c72b1eaa24837a322133b05b736f2bb"

      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.4.1/aws-ssm-params-v0.4.1-darwin-arm64.tar.gz"
      sha256 "f0016b6ad1e377a846db913108acce2e1a895312c8d593abc217156b3d01821c"

      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.4.1/aws-ssm-params-v0.4.1-linux-amd64.tar.gz"
      sha256 "af4b5088bbf8507e388855c96ff3fa6e2560c7140fc5947437c568994d9d9c6d"
      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.4.1/aws-ssm-params-v0.4.1-linux-arm64.tar.gz"
      sha256 "3a80ad2d1101ee61376e3437d135b78f5899e7deaea133376f5bce3959f8c6bf"
      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
  end

  test do
    system "#{bin}/aws-ssm-params", "--version"
  end
end
