# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsmParams < Formula
  desc "Terminal UI and CLI for AWS SSM Parameter Store"
  homepage "https://github.com/biptec/aws-ssm-params"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.3.1/aws-ssm-params-v0.3.1-darwin-amd64.tar.gz"
      sha256 "05c35ab3bcfff48d420612b2b507022cfb1ffe5a6329f0e5f77d97b8cfcddbaf"

      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.3.1/aws-ssm-params-v0.3.1-darwin-arm64.tar.gz"
      sha256 "79186705047e5d2a6040acfb0ac138246cb93eac39e41a119a2cb34bb3765ef9"

      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.3.1/aws-ssm-params-v0.3.1-linux-amd64.tar.gz"
      sha256 "75d4e73d8a982e868f130a1186cef70ca0d9b3aeb456701ee3f88811d76b7432"
      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/biptec/aws-ssm-params/releases/download/v0.3.1/aws-ssm-params-v0.3.1-linux-arm64.tar.gz"
      sha256 "33554bc83d5ec9cf3e05e32c8ec4a63f93fcdba148dfac14920f8356e3046328"
      define_method(:install) do
        bin.install "aws-ssm-params"
      end
    end
  end

  test do
    system "#{bin}/aws-ssm-params", "--help"
  end
end
